/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupPatientRouteImport } from './routes/signup.patient'
import { Route as SignupExpertRouteImport } from './routes/signup.expert'
import { Route as CommunitiesNewRouteImport } from './routes/communities.new'
import { Route as CommunitiesIdRouteImport } from './routes/communities.$id'
import { Route as ApiReferralsRouteImport } from './routes/api/referrals'
import { Route as ApiRealtimeTokenRouteImport } from './routes/api/realtime-token'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminExpertsRouteImport } from './routes/admin.experts'
import { Route as CommunitiesIdSettingsRouteImport } from './routes/communities.$id.settings'
import { Route as ApiConversationsIdMessagesRouteImport } from './routes/api/conversations.$id.messages'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPatientRoute = SignupPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => SignupRoute,
} as any)
const SignupExpertRoute = SignupExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => SignupRoute,
} as any)
const CommunitiesNewRoute = CommunitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CommunitiesRoute,
} as any)
const CommunitiesIdRoute = CommunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunitiesRoute,
} as any)
const ApiReferralsRoute = ApiReferralsRouteImport.update({
  id: '/api/referrals',
  path: '/api/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeTokenRoute = ApiRealtimeTokenRouteImport.update({
  id: '/api/realtime-token',
  path: '/api/realtime-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExpertsRoute = AdminExpertsRouteImport.update({
  id: '/admin/experts',
  path: '/admin/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIdSettingsRoute = CommunitiesIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CommunitiesIdRoute,
} as any)
const ApiConversationsIdMessagesRoute =
  ApiConversationsIdMessagesRouteImport.update({
    id: '/$id/messages',
    path: '/$id/messages',
    getParentRoute: () => ApiConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expert': typeof ExpertRoute
  '/experts': typeof ExpertsRoute
  '/feed': typeof FeedRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRouteWithChildren
  '/voice': typeof VoiceRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/realtime-token': typeof ApiRealtimeTokenRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/communities/$id': typeof CommunitiesIdRouteWithChildren
  '/communities/new': typeof CommunitiesNewRoute
  '/signup/expert': typeof SignupExpertRoute
  '/signup/patient': typeof SignupPatientRoute
  '/communities/$id/settings': typeof CommunitiesIdSettingsRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expert': typeof ExpertRoute
  '/experts': typeof ExpertsRoute
  '/feed': typeof FeedRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRouteWithChildren
  '/voice': typeof VoiceRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/realtime-token': typeof ApiRealtimeTokenRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/communities/$id': typeof CommunitiesIdRouteWithChildren
  '/communities/new': typeof CommunitiesNewRoute
  '/signup/expert': typeof SignupExpertRoute
  '/signup/patient': typeof SignupPatientRoute
  '/communities/$id/settings': typeof CommunitiesIdSettingsRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expert': typeof ExpertRoute
  '/experts': typeof ExpertsRoute
  '/feed': typeof FeedRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRouteWithChildren
  '/voice': typeof VoiceRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/realtime-token': typeof ApiRealtimeTokenRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/communities/$id': typeof CommunitiesIdRouteWithChildren
  '/communities/new': typeof CommunitiesNewRoute
  '/signup/expert': typeof SignupExpertRoute
  '/signup/patient': typeof SignupPatientRoute
  '/communities/$id/settings': typeof CommunitiesIdSettingsRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/communities'
    | '/dashboard'
    | '/expert'
    | '/experts'
    | '/feed'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/signup'
    | '/voice'
    | '/admin/experts'
    | '/api/chat'
    | '/api/conversations'
    | '/api/realtime-token'
    | '/api/referrals'
    | '/communities/$id'
    | '/communities/new'
    | '/signup/expert'
    | '/signup/patient'
    | '/communities/$id/settings'
    | '/api/conversations/$id/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/communities'
    | '/dashboard'
    | '/expert'
    | '/experts'
    | '/feed'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/signup'
    | '/voice'
    | '/admin/experts'
    | '/api/chat'
    | '/api/conversations'
    | '/api/realtime-token'
    | '/api/referrals'
    | '/communities/$id'
    | '/communities/new'
    | '/signup/expert'
    | '/signup/patient'
    | '/communities/$id/settings'
    | '/api/conversations/$id/messages'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/communities'
    | '/dashboard'
    | '/expert'
    | '/experts'
    | '/feed'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/signup'
    | '/voice'
    | '/admin/experts'
    | '/api/chat'
    | '/api/conversations'
    | '/api/realtime-token'
    | '/api/referrals'
    | '/communities/$id'
    | '/communities/new'
    | '/signup/expert'
    | '/signup/patient'
    | '/communities/$id/settings'
    | '/api/conversations/$id/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExpertRoute: typeof ExpertRoute
  ExpertsRoute: typeof ExpertsRoute
  FeedRoute: typeof FeedRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRouteWithChildren
  VoiceRoute: typeof VoiceRoute
  AdminExpertsRoute: typeof AdminExpertsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiRealtimeTokenRoute: typeof ApiRealtimeTokenRoute
  ApiReferralsRoute: typeof ApiReferralsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/patient': {
      id: '/signup/patient'
      path: '/patient'
      fullPath: '/signup/patient'
      preLoaderRoute: typeof SignupPatientRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/expert': {
      id: '/signup/expert'
      path: '/expert'
      fullPath: '/signup/expert'
      preLoaderRoute: typeof SignupExpertRouteImport
      parentRoute: typeof SignupRoute
    }
    '/communities/new': {
      id: '/communities/new'
      path: '/new'
      fullPath: '/communities/new'
      preLoaderRoute: typeof CommunitiesNewRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/communities/$id': {
      id: '/communities/$id'
      path: '/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof CommunitiesIdRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/api/referrals': {
      id: '/api/referrals'
      path: '/api/referrals'
      fullPath: '/api/referrals'
      preLoaderRoute: typeof ApiReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime-token': {
      id: '/api/realtime-token'
      path: '/api/realtime-token'
      fullPath: '/api/realtime-token'
      preLoaderRoute: typeof ApiRealtimeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/experts': {
      id: '/admin/experts'
      path: '/admin/experts'
      fullPath: '/admin/experts'
      preLoaderRoute: typeof AdminExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$id/settings': {
      id: '/communities/$id/settings'
      path: '/settings'
      fullPath: '/communities/$id/settings'
      preLoaderRoute: typeof CommunitiesIdSettingsRouteImport
      parentRoute: typeof CommunitiesIdRoute
    }
    '/api/conversations/$id/messages': {
      id: '/api/conversations/$id/messages'
      path: '/$id/messages'
      fullPath: '/api/conversations/$id/messages'
      preLoaderRoute: typeof ApiConversationsIdMessagesRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
  }
}

interface CommunitiesIdRouteChildren {
  CommunitiesIdSettingsRoute: typeof CommunitiesIdSettingsRoute
}

const CommunitiesIdRouteChildren: CommunitiesIdRouteChildren = {
  CommunitiesIdSettingsRoute: CommunitiesIdSettingsRoute,
}

const CommunitiesIdRouteWithChildren = CommunitiesIdRoute._addFileChildren(
  CommunitiesIdRouteChildren,
)

interface CommunitiesRouteChildren {
  CommunitiesIdRoute: typeof CommunitiesIdRouteWithChildren
  CommunitiesNewRoute: typeof CommunitiesNewRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesIdRoute: CommunitiesIdRouteWithChildren,
  CommunitiesNewRoute: CommunitiesNewRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

interface SignupRouteChildren {
  SignupExpertRoute: typeof SignupExpertRoute
  SignupPatientRoute: typeof SignupPatientRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupExpertRoute: SignupExpertRoute,
  SignupPatientRoute: SignupPatientRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

interface ApiConversationsRouteChildren {
  ApiConversationsIdMessagesRoute: typeof ApiConversationsIdMessagesRoute
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsIdMessagesRoute: ApiConversationsIdMessagesRoute,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExpertRoute: ExpertRoute,
  ExpertsRoute: ExpertsRoute,
  FeedRoute: FeedRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRouteWithChildren,
  VoiceRoute: VoiceRoute,
  AdminExpertsRoute: AdminExpertsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiRealtimeTokenRoute: ApiRealtimeTokenRoute,
  ApiReferralsRoute: ApiReferralsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
