/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReferralsRouteImport } from './routes/api/referrals'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminExpertsRouteImport } from './routes/admin.experts'
import { Route as ApiConversationsIdMessagesRouteImport } from './routes/api/conversations.$id.messages'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsRoute = ApiReferralsRouteImport.update({
  id: '/api/referrals',
  path: '/api/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExpertsRoute = AdminExpertsRouteImport.update({
  id: '/admin/experts',
  path: '/admin/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIdMessagesRoute =
  ApiConversationsIdMessagesRouteImport.update({
    id: '/$id/messages',
    path: '/$id/messages',
    getParentRoute: () => ApiConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/expert': typeof ExpertRoute
  '/experts': typeof ExpertsRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/referrals': typeof ApiReferralsRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/expert': typeof ExpertRoute
  '/experts': typeof ExpertsRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/referrals': typeof ApiReferralsRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/expert': typeof ExpertRoute
  '/experts': typeof ExpertsRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/referrals': typeof ApiReferralsRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/expert'
    | '/experts'
    | '/feed'
    | '/login'
    | '/signup'
    | '/admin/experts'
    | '/api/chat'
    | '/api/conversations'
    | '/api/referrals'
    | '/api/conversations/$id/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/expert'
    | '/experts'
    | '/feed'
    | '/login'
    | '/signup'
    | '/admin/experts'
    | '/api/chat'
    | '/api/conversations'
    | '/api/referrals'
    | '/api/conversations/$id/messages'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/expert'
    | '/experts'
    | '/feed'
    | '/login'
    | '/signup'
    | '/admin/experts'
    | '/api/chat'
    | '/api/conversations'
    | '/api/referrals'
    | '/api/conversations/$id/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  ExpertRoute: typeof ExpertRoute
  ExpertsRoute: typeof ExpertsRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminExpertsRoute: typeof AdminExpertsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiReferralsRoute: typeof ApiReferralsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals': {
      id: '/api/referrals'
      path: '/api/referrals'
      fullPath: '/api/referrals'
      preLoaderRoute: typeof ApiReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/experts': {
      id: '/admin/experts'
      path: '/admin/experts'
      fullPath: '/admin/experts'
      preLoaderRoute: typeof AdminExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id/messages': {
      id: '/api/conversations/$id/messages'
      path: '/$id/messages'
      fullPath: '/api/conversations/$id/messages'
      preLoaderRoute: typeof ApiConversationsIdMessagesRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
  }
}

interface ApiConversationsRouteChildren {
  ApiConversationsIdMessagesRoute: typeof ApiConversationsIdMessagesRoute
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsIdMessagesRoute: ApiConversationsIdMessagesRoute,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  ExpertRoute: ExpertRoute,
  ExpertsRoute: ExpertsRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminExpertsRoute: AdminExpertsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiReferralsRoute: ApiReferralsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
